language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gfortran python python-dev subversion git swig
  - git clone https://github.com/bumps/bumps.git
  - sudo -H pip install ./bumps
install:
  - "./build.sh"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
# command to run tests
script:
  - cd hklgen
  - PYTHONPATH=$PYTHONPATH:. nosetests
