language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gfortran python python-dev python-numpy python-scipy python-matplotlib python-pip subversion git swig
  - git clone https://github.com/bumps/bumps.git
  - sudo pip install ./bumps
  - sudo pip install nose pylab
install:
  - "./build.sh"
# command to run tests
script:
  - cd hklgen
  - PYTHONPATH=. nosetests
